root: /data/ligerlac/17180303-small-mixed/1100fb/
train:
- [recon3D_sf1.parquet, labels_sf1.parquet]
- [recon3D_sf2.parquet, labels_sf2.parquet]
- [recon3D_sf3.parquet, labels_sf3.parquet]
- [recon3D_sf4.parquet, labels_sf4.parquet]
- [recon3D_sf5.parquet, labels_sf5.parquet]
- [recon3D_sf6.parquet, labels_sf6.parquet]
- [recon3D_sf7.parquet, labels_sf7.parquet]

test:
- [recon3D_sf8.parquet, labels_sf8.parquet]
- [recon3D_sf9.parquet, labels_sf9.parquet]

scaling:
  mean_X: [0.4]
  std_X: [2]
  mean_y: [-1, -0.01, 100.0, 0.05, -0.001, -2., 50000., -0.001, 0.01, -0.02, 7.e-05, -0.01, -0.2]
  std_y: [250, 10., 0.0, 10., 0.5, 0.5, 20000., 5., 2., 5., 0.1, 10., 50.]
